#!/bin/sh

#API=localhost:1337/api/country/create
API="5.101.119.187/api/country/create"

curl ${API} -d code=AF --data-urlencode "name=Afghanistan" 
curl ${API} -d code=AX --data-urlencode "name=Aland Islands" 
curl ${API} -d code=AL --data-urlencode "name=Albania" 
curl ${API} -d code=DZ --data-urlencode "name=Algeria" 
curl ${API} -d code=AS --data-urlencode "name=American Samoa" 
curl ${API} -d code=AD --data-urlencode "name=Andorra" 
curl ${API} -d code=AO --data-urlencode "name=Angola" 
curl ${API} -d code=AI --data-urlencode "name=Anguilla" 
curl ${API} -d code=AQ --data-urlencode "name=Antarctica" 
curl ${API} -d code=AG --data-urlencode "name=Antigua & Barbuda" 
curl ${API} -d code=AR --data-urlencode "name=Argentina" 
curl ${API} -d code=AM --data-urlencode "name=Armenia" 
curl ${API} -d code=AW --data-urlencode "name=Aruba" 
curl ${API} -d code=AU --data-urlencode "name=Australia" 
curl ${API} -d code=AT --data-urlencode "name=Austria" 
curl ${API} -d code=AZ --data-urlencode "name=Azerbaijan" 
curl ${API} -d code=BS --data-urlencode "name=Bahamas, The" 
curl ${API} -d code=BH --data-urlencode "name=Bahrain" 
curl ${API} -d code=BD --data-urlencode "name=Bangladesh" 
curl ${API} -d code=BB --data-urlencode "name=Barbados" 
curl ${API} -d code=BY --data-urlencode "name=Belarus" 
curl ${API} -d code=BE --data-urlencode "name=Belgium" 
curl ${API} -d code=BZ --data-urlencode "name=Belize" 
curl ${API} -d code=BJ --data-urlencode "name=Benin" 
curl ${API} -d code=BM --data-urlencode "name=Bermuda" 
curl ${API} -d code=BT --data-urlencode "name=Bhutan" 
curl ${API} -d code=BO --data-urlencode "name=Bolivia" 
curl ${API} -d code=BQ --data-urlencode "name=Bonaire, St.Eustat, Saba" 
curl ${API} -d code=BA --data-urlencode "name=Bosnia and Herzegovina" 
curl ${API} -d code=BW --data-urlencode "name=Botswana" 
curl ${API} -d code=BV --data-urlencode "name=Bouvet Island" 
curl ${API} -d code=BR --data-urlencode "name=Brazil" 
curl ${API} -d code=IO --data-urlencode "name=British Indian Ocean T." 
curl ${API} -d code=VG --data-urlencode "name=British Virgin Islands" 
curl ${API} -d code=BN --data-urlencode "name=Brunei Darussalam" 
curl ${API} -d code=BG --data-urlencode "name=Bulgaria" 
curl ${API} -d code=BF --data-urlencode "name=Burkina Faso" 
curl ${API} -d code=BI --data-urlencode "name=Burundi" 
curl ${API} -d code=CV --data-urlencode "name=Cabo Verde" 
curl ${API} -d code=KH --data-urlencode "name=Cambodia" 
curl ${API} -d code=CM --data-urlencode "name=Cameroon" 
curl ${API} -d code=CA --data-urlencode "name=Canada" 
curl ${API} -d code=KY --data-urlencode "name=Cayman Islands" 
curl ${API} -d code=CF --data-urlencode "name=Central African Republic" 
curl ${API} -d code=TD --data-urlencode "name=Chad" 
curl ${API} -d code=CL --data-urlencode "name=Chile" 
curl ${API} -d code=CN --data-urlencode "name=China" 
curl ${API} -d code=CX --data-urlencode "name=Christmas Island" 
curl ${API} -d code=CC --data-urlencode "name=Cocos (Keeling) Islands" 
curl ${API} -d code=CO --data-urlencode "name=Colombia" 
curl ${API} -d code=KM --data-urlencode "name=Comoros" 
curl ${API} -d code=CG --data-urlencode "name=Congo" 
curl ${API} -d code=CD --data-urlencode "name=Congo, Dem. Rep. of the" 
curl ${API} -d code=CK --data-urlencode "name=Cook Islands" 
curl ${API} -d code=CR --data-urlencode "name=Costa Rica" 
curl ${API} -d code=CI --data-urlencode "name=Cote D'Ivoire" 
curl ${API} -d code=HR --data-urlencode "name=Croatia" 
curl ${API} -d code=CU --data-urlencode "name=Cuba" 
curl ${API} -d code=CW --data-urlencode "name=Curacao" 
curl ${API} -d code=CY --data-urlencode "name=Cyprus" 
curl ${API} -d code=CZ --data-urlencode "name=Czech Republic" 
curl ${API} -d code=DK --data-urlencode "name=Denmark" 
curl ${API} -d code=DJ --data-urlencode "name=Djibouti" 
curl ${API} -d code=DM --data-urlencode "name=Dominica" 
curl ${API} -d code=DO --data-urlencode "name=Dominican Republic" 
curl ${API} -d code=TP --data-urlencode "name=East Timor (Timor-Leste)" 
curl ${API} -d code=EC --data-urlencode "name=Ecuador" 
curl ${API} -d code=EG --data-urlencode "name=Egypt" 
curl ${API} -d code=SV --data-urlencode "name=El Salvador" 
curl ${API} -d code=GQ --data-urlencode "name=Equatorial Guinea" 
curl ${API} -d code=ER --data-urlencode "name=Eritrea" 
curl ${API} -d code=EE --data-urlencode "name=Estonia" 
curl ${API} -d code=ET --data-urlencode "name=Ethiopia" 
curl ${API} -d code=FO --data-urlencode "name=Faroe Islands" 
curl ${API} -d code=FJ --data-urlencode "name=Fiji" 
curl ${API} -d code=FI --data-urlencode "name=Finland" 
curl ${API} -d code=FR --data-urlencode "name=France" 
curl ${API} -d code=GF --data-urlencode "name=French Guiana" 
curl ${API} -d code=PF --data-urlencode "name=French Polynesia" 
curl ${API} -d code=TF --data-urlencode "name=French Southern Terr." 
curl ${API} -d code=GA --data-urlencode "name=Gabon" 
curl ${API} -d code=GM --data-urlencode "name=Gambia, the" 
curl ${API} -d code=GE --data-urlencode "name=Georgia" 
curl ${API} -d code=DE --data-urlencode "name=Germany" 
curl ${API} -d code=GH --data-urlencode "name=Ghana" 
curl ${API} -d code=GI --data-urlencode "name=Gibraltar" 
curl ${API} -d code=GR --data-urlencode "name=Greece" 
curl ${API} -d code=GL --data-urlencode "name=Greenland" 
curl ${API} -d code=GD --data-urlencode "name=Grenada" 
curl ${API} -d code=GP --data-urlencode "name=Guadeloupe" 
curl ${API} -d code=GU --data-urlencode "name=Guam" 
curl ${API} -d code=GT --data-urlencode "name=Guatemala" 
curl ${API} -d code=GG --data-urlencode "name=Guernsey and Alderney" 
curl ${API} -d code=GN --data-urlencode "name=Guinea" 
curl ${API} -d code=GW --data-urlencode "name=Guinea-Bissau" 
curl ${API} -d code=GP --data-urlencode "name=Guinea, Equatorial" 
curl ${API} -d code=GY --data-urlencode "name=Guyana" 
curl ${API} -d code=HT --data-urlencode "name=Haiti" 
curl ${API} -d code=HM --data-urlencode "name=Heard & McDonald Is.(AU)" 
curl ${API} -d code=HN --data-urlencode "name=Honduras" 
curl ${API} -d code=HK --data-urlencode "name=Hong Kong, (China)" 
curl ${API} -d code=HU --data-urlencode "name=Hungary" 
curl ${API} -d code=IS --data-urlencode "name=Iceland" 
curl ${API} -d code=IN --data-urlencode "name=India" 
curl ${API} -d code=ID --data-urlencode "name=Indonesia" 
curl ${API} -d code=IR --data-urlencode "name=Iran, Islamic Republic of" 
curl ${API} -d code=IQ --data-urlencode "name=Iraq" 
curl ${API} -d code=IE --data-urlencode "name=Ireland" 
curl ${API} -d code=IL --data-urlencode "name=Israel" 
curl ${API} -d code=IT --data-urlencode "name=Italy" 
curl ${API} -d code=JM --data-urlencode "name=Jamaica" 
curl ${API} -d code=JP --data-urlencode "name=Japan" 
curl ${API} -d code=JE --data-urlencode "name=Jersey" 
curl ${API} -d code=JO --data-urlencode "name=Jordan" 
curl ${API} -d code=KZ --data-urlencode "name=Kazakhstan" 
curl ${API} -d code=KE --data-urlencode "name=Kenya" 
curl ${API} -d code=KI --data-urlencode "name=Kiribati" 
curl ${API} -d code=KP --data-urlencode "name=Korea Dem. People's Rep." 
curl ${API} -d code=KR --data-urlencode "name=Korea, (South) Republic of" 
curl ${API} -d code=KV --data-urlencode "name=Kosovo" 
curl ${API} -d code=KW --data-urlencode "name=Kuwait" 
curl ${API} -d code=KG --data-urlencode "name=Kyrgyzstan" 
curl ${API} -d code=LA --data-urlencode "name=Lao People's Democ. Rep." 
curl ${API} -d code=LV --data-urlencode "name=Latvia" 
curl ${API} -d code=LB --data-urlencode "name=Lebanon" 
curl ${API} -d code=LS --data-urlencode "name=Lesotho" 
curl ${API} -d code=LR --data-urlencode "name=Liberia" 
curl ${API} -d code=LY --data-urlencode "name=Libyan Arab Jamahiriya" 
curl ${API} -d code=LI --data-urlencode "name=Liechtenstein" 
curl ${API} -d code=LT --data-urlencode "name=Lithuania" 
curl ${API} -d code=LU --data-urlencode "name=Luxembourg" 
curl ${API} -d code=MO --data-urlencode "name=Macao, (China)" 
curl ${API} -d code=MK --data-urlencode "name=Macedonia, TFYR" 
curl ${API} -d code=MG --data-urlencode "name=Madagascar" 
curl ${API} -d code=MW --data-urlencode "name=Malawi" 
curl ${API} -d code=MY --data-urlencode "name=Malaysia" 
curl ${API} -d code=MV --data-urlencode "name=Maldives" 
curl ${API} -d code=ML --data-urlencode "name=Mali" 
curl ${API} -d code=MT --data-urlencode "name=Malta" 
curl ${API} -d code=IM --data-urlencode "name=Man, Isle of" 
curl ${API} -d code=MH --data-urlencode "name=Marshall Islands" 
curl ${API} -d code=MQ --data-urlencode "name=Martinique (FR)" 
curl ${API} -d code=MR --data-urlencode "name=Mauritania" 
curl ${API} -d code=MU --data-urlencode "name=Mauritius" 
curl ${API} -d code=YT --data-urlencode "name=Mayotte (FR)" 
curl ${API} -d code=MX --data-urlencode "name=Mexico" 
curl ${API} -d code=FM --data-urlencode "name=Micronesia, Fed. States of" 
curl ${API} -d code=MD --data-urlencode "name=Moldova, Republic of" 
curl ${API} -d code=MC --data-urlencode "name=Monaco" 
curl ${API} -d code=MN --data-urlencode "name=Mongolia" 
curl ${API} -d code=CS --data-urlencode "name=Montenegro" 
curl ${API} -d code=MS --data-urlencode "name=Montserrat" 
curl ${API} -d code=MA --data-urlencode "name=Morocco" 
curl ${API} -d code=MZ --data-urlencode "name=Mozambique" 
curl ${API} -d code=MM --data-urlencode "name=Myanmar (ex-Burma)" 
curl ${API} -d code=NA --data-urlencode "name=Namibia" 
curl ${API} -d code=NR --data-urlencode "name=Nauru" 
curl ${API} -d code=NP --data-urlencode "name=Nepal" 
curl ${API} -d code=NL --data-urlencode "name=Netherlands" 
curl ${API} -d code=AN --data-urlencode "name=Netherlands Antilles" 
curl ${API} -d code=NC --data-urlencode "name=New Caledonia" 
curl ${API} -d code=NZ --data-urlencode "name=New Zealand" 
curl ${API} -d code=NI --data-urlencode "name=Nicaragua" 
curl ${API} -d code=NE --data-urlencode "name=Niger" 
curl ${API} -d code=NG --data-urlencode "name=Nigeria" 
curl ${API} -d code=NU --data-urlencode "name=Niue" 
curl ${API} -d code=NF --data-urlencode "name=Norfolk Island" 
curl ${API} -d code=MP --data-urlencode "name=Northern Mariana Islands" 
curl ${API} -d code=NO --data-urlencode "name=Norway" 
curl ${API} -d code=OM --data-urlencode "name=Oman" 
curl ${API} -d code=PK --data-urlencode "name=Pakistan" 
curl ${API} -d code=PW --data-urlencode "name=Palau" 
curl ${API} -d code=PS --data-urlencode "name=Palestinian Territory" 
curl ${API} -d code=PA --data-urlencode "name=Panama" 
curl ${API} -d code=PG --data-urlencode "name=Papua New Guinea" 
curl ${API} -d code=PY --data-urlencode "name=Paraguay" 
curl ${API} -d code=PE --data-urlencode "name=Peru" 
curl ${API} -d code=PH --data-urlencode "name=Philippines" 
curl ${API} -d code=PN --data-urlencode "name=Pitcairn Island" 
curl ${API} -d code=PL --data-urlencode "name=Poland" 
curl ${API} -d code=PT --data-urlencode "name=Portugal" 
curl ${API} -d code=PR --data-urlencode "name=Puerto Rico" 
curl ${API} -d code=QA --data-urlencode "name=Qatar" 
curl ${API} -d code=RE --data-urlencode "name=Reunion (FR)" 
curl ${API} -d code=RU --data-urlencode "name=Russia (Russian Fed.)" 
curl ${API} -d code=RW --data-urlencode "name=Rwanda" 
curl ${API} -d code=BL --data-urlencode "name=Saint Barthelemy (FR)" 
curl ${API} -d code=SH --data-urlencode "name=Saint Helena (UK)" 
curl ${API} -d code=KN --data-urlencode "name=Saint Kitts and Nevis" 
curl ${API} -d code=MF --data-urlencode "name=Saint Martin (FR)" 
curl ${API} -d code=PM --data-urlencode "name=S Pierre & Miquelon(FR)" 
curl ${API} -d code=VC --data-urlencode "name=S Vincent & Grenadines" 
curl ${API} -d code=SM --data-urlencode "name=San Marino" 
curl ${API} -d code=ST --data-urlencode "name=Sao Tome and Principe" 
curl ${API} -d code=SA --data-urlencode "name=Saudi Arabia" 
curl ${API} -d code=SN --data-urlencode "name=Senegal" 
curl ${API} -d code=RS --data-urlencode "name=Serbia" 
curl ${API} -d code=SC --data-urlencode "name=Seychelles" 
curl ${API} -d code=SG --data-urlencode "name=Singapore" 
curl ${API} -d code=SK --data-urlencode "name=Slovakia" 
curl ${API} -d code=SI --data-urlencode "name=Slovenia" 
curl ${API} -d code=SB --data-urlencode "name=Solomon Islands" 
curl ${API} -d code=SO --data-urlencode "name=Somalia" 
curl ${API} -d code=ZA --data-urlencode "name=South Africa" 
curl ${API} -d code=GS --data-urlencode "name=S.George & S.Sandwich" 
curl ${API} -d code=SS --data-urlencode "name=South Sudan" 
curl ${API} -d code=ES --data-urlencode "name=Spain" 
curl ${API} -d code=LK --data-urlencode "name=Sri Lanka (ex-Ceilan)" 
curl ${API} -d code=SD --data-urlencode "name=Sudan" 
curl ${API} -d code=SR --data-urlencode "name=Suriname" 
curl ${API} -d code=SJ --data-urlencode "name=Svalbard & Jan Mayen Is." 
curl ${API} -d code=SZ --data-urlencode "name=Swaziland" 
curl ${API} -d code=SE --data-urlencode "name=Sweden" 
curl ${API} -d code=CH --data-urlencode "name=Switzerland" 
curl ${API} -d code=SY --data-urlencode "name=Syrian Arab Republic" 
curl ${API} -d code=TW --data-urlencode "name=Taiwan" 
curl ${API} -d code=TJ --data-urlencode "name=Tajikistan" 
curl ${API} -d code=TZ --data-urlencode "name=Tanzania, United Rep. of" 
curl ${API} -d code=TH --data-urlencode "name=Thailand" 
curl ${API} -d code=TG --data-urlencode "name=Togo" 
curl ${API} -d code=TK --data-urlencode "name=Tokelau" 
curl ${API} -d code=TO --data-urlencode "name=Tonga" 
curl ${API} -d code=TT --data-urlencode "name=Trinidad & Tobago" 
curl ${API} -d code=TN --data-urlencode "name=Tunisia" 
curl ${API} -d code=TR --data-urlencode "name=Turkey" 
curl ${API} -d code=TM --data-urlencode "name=Turkmenistan" 
curl ${API} -d code=TC --data-urlencode "name=Turks and Caicos Is." 
curl ${API} -d code=TV --data-urlencode "name=Tuvalu" 
curl ${API} -d code=UG --data-urlencode "name=Uganda" 
curl ${API} -d code=UA --data-urlencode "name=Ukraine" 
curl ${API} -d code=AE --data-urlencode "name=United Arab Emirates" 
curl ${API} -d code=UK --data-urlencode "name=United Kingdom" 
curl ${API} -d code=US --data-urlencode "name=United States" 
curl ${API} -d code=UM --data-urlencode "name=US Minor Outlying Isl." 
curl ${API} -d code=UY --data-urlencode "name=Uruguay" 
curl ${API} -d code=UZ --data-urlencode "name=Uzbekistan" 
curl ${API} -d code=VU --data-urlencode "name=Vanuatu" 
curl ${API} -d code=VA --data-urlencode "name=Vatican (Holy See)" 
curl ${API} -d code=VE --data-urlencode "name=Venezuela" 
curl ${API} -d code=VN --data-urlencode "name=Viet Nam" 
curl ${API} -d code=VI --data-urlencode "name=Virgin Islands, U.S." 
curl ${API} -d code=WF --data-urlencode "name=Wallis and Futuna" 
curl ${API} -d code=EH --data-urlencode "name=Western Sahara" 
curl ${API} -d code=YE --data-urlencode "name=Yemen" 
curl ${API} -d code=ZM --data-urlencode "name=Zambia" 
curl ${API} -d code=ZW --data-urlencode "name=Zimbabwe" 
