#!/bin/sh

API=localhost:1337/api/country/create
#API="5.178.85.110/api/country/create"

curl ${API} -d code=AF --data-urlencode "name=Afghanistan" --data-urlencode "name_ru=Афганистан"
curl ${API} -d code=AX --data-urlencode "name=Aland Islands" --data-urlencode "name_ru=Аландские острова"
curl ${API} -d code=AL --data-urlencode "name=Albania" --data-urlencode "name_ru=Албания"
curl ${API} -d code=DZ --data-urlencode "name=Algeria" --data-urlencode "name_ru=Алжир"
curl ${API} -d code=AS --data-urlencode "name=American Samoa" --data-urlencode "name_ru=Американское Самоа"
curl ${API} -d code=AD --data-urlencode "name=Andorra" --data-urlencode "name_ru=Андорра"
curl ${API} -d code=AO --data-urlencode "name=Angola" --data-urlencode "name_ru=Ангола"
curl ${API} -d code=AI --data-urlencode "name=Anguilla" --data-urlencode "name_ru=Ангилья"
curl ${API} -d code=AQ --data-urlencode "name=Antarctica" --data-urlencode "name_ru=Антарктида"
curl ${API} -d code=AG --data-urlencode "name=Antigua & Barbuda" --data-urlencode "name_ru=Антигуа и Барбуда"
curl ${API} -d code=AR --data-urlencode "name=Argentina" --data-urlencode "name_ru=Аргентина"
curl ${API} -d code=AM --data-urlencode "name=Armenia" --data-urlencode "name_ru=Армения"
curl ${API} -d code=AW --data-urlencode "name=Aruba" --data-urlencode "name_ru=Аруба"
curl ${API} -d code=AU --data-urlencode "name=Australia" --data-urlencode "name_ru=Австралия"
curl ${API} -d code=AT --data-urlencode "name=Austria" --data-urlencode "name_ru=Австрия"
curl ${API} -d code=AZ --data-urlencode "name=Azerbaijan" --data-urlencode "name_ru=Азербайджан"
curl ${API} -d code=BS --data-urlencode "name=Bahamas, The" --data-urlencode "name_ru=Багамские острова"
curl ${API} -d code=BH --data-urlencode "name=Bahrain" --data-urlencode "name_ru=Бахрейн"
curl ${API} -d code=BD --data-urlencode "name=Bangladesh" --data-urlencode "name_ru=Бангладеш"
curl ${API} -d code=BB --data-urlencode "name=Barbados" --data-urlencode "name_ru=Барбадос"
curl ${API} -d code=BY --data-urlencode "name=Belarus" --data-urlencode "name_ru=Беларусь"
curl ${API} -d code=BE --data-urlencode "name=Belgium" --data-urlencode "name_ru=Бельгия"
curl ${API} -d code=BZ --data-urlencode "name=Belize" --data-urlencode "name_ru=Белиз"
curl ${API} -d code=BJ --data-urlencode "name=Benin" --data-urlencode "name_ru=Бенин"
curl ${API} -d code=BM --data-urlencode "name=Bermuda" --data-urlencode "name_ru=Бермудские острова"
curl ${API} -d code=BT --data-urlencode "name=Bhutan" --data-urlencode "name_ru=Бутан"
curl ${API} -d code=BO --data-urlencode "name=Bolivia" --data-urlencode "name_ru=Боливия"
curl ${API} -d code=BQ --data-urlencode "name=Bonaire, St.Eustat, Saba" --data-urlencode "name_ru=Бонайре, Саба"
curl ${API} -d code=BA --data-urlencode "name=Bosnia and Herzegovina" --data-urlencode "name_ru=Босния и Герцеговина"
curl ${API} -d code=BW --data-urlencode "name=Botswana" --data-urlencode "name_ru=Ботсвана"
curl ${API} -d code=BV --data-urlencode "name=Bouvet Island" --data-urlencode "name_ru=Виргинские острова"
curl ${API} -d code=BR --data-urlencode "name=Brazil" --data-urlencode "name_ru=Бразилия"
curl ${API} -d code=IO --data-urlencode "name=British Indian Ocean T." --data-urlencode "name_ru=Британская территория в Индийском океане Т."
curl ${API} -d code=VG --data-urlencode "name=British Virgin Islands" --data-urlencode "name_ru=Британские Виргинские острова"
curl ${API} -d code=BN --data-urlencode "name=Brunei Darussalam" --data-urlencode "name_ru=Бруней-Даруссалам"
curl ${API} -d code=BG --data-urlencode "name=Bulgaria" --data-urlencode "name_ru=Болгария"
curl ${API} -d code=BF --data-urlencode "name=Burkina Faso" --data-urlencode "name_ru=Буркина-Фасо"
curl ${API} -d code=BI --data-urlencode "name=Burundi" --data-urlencode "name_ru=Бурунди"
curl ${API} -d code=CV --data-urlencode "name=Cabo Verde" --data-urlencode "name_ru=Кабо -Верде"
curl ${API} -d code=KH --data-urlencode "name=Cambodia" --data-urlencode "name_ru=Камбоджа"
curl ${API} -d code=CM --data-urlencode "name=Cameroon" --data-urlencode "name_ru=Камерун"
curl ${API} -d code=CA --data-urlencode "name=Canada" --data-urlencode "name_ru=Канада"
curl ${API} -d code=KY --data-urlencode "name=Cayman Islands" --data-urlencode "name_ru=Каймановы острова"
curl ${API} -d code=CF --data-urlencode "name=Central African Republic" --data-urlencode "name_ru=Центрально-Африканская Республика"
curl ${API} -d code=TD --data-urlencode "name=Chad" --data-urlencode "name_ru=Чад"
curl ${API} -d code=CL --data-urlencode "name=Chile" --data-urlencode "name_ru=Чили"
curl ${API} -d code=CN --data-urlencode "name=China" --data-urlencode "name_ru=Китай"
curl ${API} -d code=CX --data-urlencode "name=Christmas Island" --data-urlencode "name_ru=Остров Рождества"
curl ${API} -d code=CC --data-urlencode "name=Cocos (Keeling) Islands" --data-urlencode "name_ru=Кокосовые (Килинг) острова"
curl ${API} -d code=CO --data-urlencode "name=Colombia" --data-urlencode "name_ru=Колумбия"
curl ${API} -d code=KM --data-urlencode "name=Comoros" --data-urlencode "name_ru=Коморские острова"
curl ${API} -d code=CG --data-urlencode "name=Congo" --data-urlencode "name_ru=Конго"
curl ${API} -d code=CD --data-urlencode "name=Congo, Dem. Rep. of the" --data-urlencode "name_ru=Конго, Дем. Респ."
curl ${API} -d code=CK --data-urlencode "name=Cook Islands" --data-urlencode "name_ru=острова Кука"
curl ${API} -d code=CR --data-urlencode "name=Costa Rica" --data-urlencode "name_ru=Коста-Рика"
curl ${API} -d code=CI --data-urlencode "name=Cote D'Ivoire" --data-urlencode "name_ru=Кот-д'Ивуар"
curl ${API} -d code=HR --data-urlencode "name=Croatia" --data-urlencode "name_ru=Хорватия"
curl ${API} -d code=CU --data-urlencode "name=Cuba" --data-urlencode "name_ru=Куба"
curl ${API} -d code=CW --data-urlencode "name=Curacao" --data-urlencode "name_ru=Кюрасао"
curl ${API} -d code=CY --data-urlencode "name=Cyprus" --data-urlencode "name_ru=Кипр"
curl ${API} -d code=CZ --data-urlencode "name=Czech Republic" --data-urlencode "name_ru=Чехия"
curl ${API} -d code=DK --data-urlencode "name=Denmark" --data-urlencode "name_ru=Дания"
curl ${API} -d code=DJ --data-urlencode "name=Djibouti" --data-urlencode "name_ru=Джибути"
curl ${API} -d code=DM --data-urlencode "name=Dominica" --data-urlencode "name_ru=Доминика"
curl ${API} -d code=DO --data-urlencode "name=Dominican Republic" --data-urlencode "name_ru=Доминиканская Республика"
curl ${API} -d code=TP --data-urlencode "name=East Timor (Timor-Leste)" --data-urlencode "name_ru=Восточный Тимор (Тимор-Лешти)"
curl ${API} -d code=EC --data-urlencode "name=Ecuador" --data-urlencode "name_ru=Эквадор"
curl ${API} -d code=EG --data-urlencode "name=Egypt" --data-urlencode "name_ru=Египет"
curl ${API} -d code=SV --data-urlencode "name=El Salvador" --data-urlencode "name_ru=Сальвадор"
curl ${API} -d code=GQ --data-urlencode "name=Equatorial Guinea" --data-urlencode "name_ru=Экваториальная Гвинея"
curl ${API} -d code=ER --data-urlencode "name=Eritrea" --data-urlencode "name_ru=Эритрея"
curl ${API} -d code=EE --data-urlencode "name=Estonia" --data-urlencode "name_ru=Эстония"
curl ${API} -d code=ET --data-urlencode "name=Ethiopia" --data-urlencode "name_ru=Эфиопия"
curl ${API} -d code=FO --data-urlencode "name=Faroe Islands" --data-urlencode "name_ru=Фарерские острова"
curl ${API} -d code=FJ --data-urlencode "name=Fiji" --data-urlencode "name_ru=Фиджи"
curl ${API} -d code=FI --data-urlencode "name=Finland" --data-urlencode "name_ru=Финляндия"
curl ${API} -d code=FR --data-urlencode "name=France" --data-urlencode "name_ru=Франция"
curl ${API} -d code=GF --data-urlencode "name=French Guiana" --data-urlencode "name_ru=Французская Гвиана"
curl ${API} -d code=PF --data-urlencode "name=French Polynesia" --data-urlencode "name_ru=Французская Полинезия"
curl ${API} -d code=TF --data-urlencode "name=French Southern Terr." --data-urlencode "name_ru=Французские южные территории."
curl ${API} -d code=GA --data-urlencode "name=Gabon" --data-urlencode "name_ru=Габон"
curl ${API} -d code=GM --data-urlencode "name=Gambia, the" --data-urlencode "name_ru=Гамбия"
curl ${API} -d code=GE --data-urlencode "name=Georgia" --data-urlencode "name_ru=Грузия"
curl ${API} -d code=DE --data-urlencode "name=Germany" --data-urlencode "name_ru=Германия"
curl ${API} -d code=GH --data-urlencode "name=Ghana" --data-urlencode "name_ru=Гана"
curl ${API} -d code=GI --data-urlencode "name=Gibraltar" --data-urlencode "name_ru=Гибралтар"
curl ${API} -d code=GR --data-urlencode "name=Greece" --data-urlencode "name_ru=Греция"
curl ${API} -d code=GL --data-urlencode "name=Greenland" --data-urlencode "name_ru=Гренландия"
curl ${API} -d code=GD --data-urlencode "name=Grenada" --data-urlencode "name_ru=Гренада"
curl ${API} -d code=GP --data-urlencode "name=Guadeloupe" --data-urlencode "name_ru=Гваделупа"
curl ${API} -d code=GU --data-urlencode "name=Guam" --data-urlencode "name_ru=Гуам"
curl ${API} -d code=GT --data-urlencode "name=Guatemala" --data-urlencode "name_ru=Гватемала"
curl ${API} -d code=GG --data-urlencode "name=Guernsey and Alderney" --data-urlencode "name_ru=Гернси и Олдерни"
curl ${API} -d code=GN --data-urlencode "name=Guinea" --data-urlencode "name_ru=Гвинея"
curl ${API} -d code=GW --data-urlencode "name=Guinea-Bissau" --data-urlencode "name_ru=Гвинея-Бисау"
curl ${API} -d code=GP --data-urlencode "name=Guinea, Equatorial" --data-urlencode "name_ru=Гвинея , Экваториальная"
curl ${API} -d code=GY --data-urlencode "name=Guyana" --data-urlencode "name_ru=Гайана"
curl ${API} -d code=HT --data-urlencode "name=Haiti" --data-urlencode "name_ru=Гаити"
curl ${API} -d code=HM --data-urlencode "name=Heard & McDonald Is.(AU)" --data-urlencode "name_ru=Херд и Макдональд. (AU)"
curl ${API} -d code=HN --data-urlencode "name=Honduras" --data-urlencode "name_ru=Гондурас"
curl ${API} -d code=HK --data-urlencode "name=Hong Kong, (China)" --data-urlencode "name_ru=Гонконг, (Китай)"
curl ${API} -d code=HU --data-urlencode "name=Hungary" --data-urlencode "name_ru=Венгрия"
curl ${API} -d code=IS --data-urlencode "name=Iceland" --data-urlencode "name_ru=Исландия"
curl ${API} -d code=IN --data-urlencode "name=India" --data-urlencode "name_ru=Индия"
curl ${API} -d code=ID --data-urlencode "name=Indonesia" --data-urlencode "name_ru=Индонезия"
curl ${API} -d code=IR --data-urlencode "name=Iran, Islamic Republic of" --data-urlencode "name_ru=Иран, Исламская Республика"
curl ${API} -d code=IQ --data-urlencode "name=Iraq" --data-urlencode "name_ru=Ирак"
curl ${API} -d code=IE --data-urlencode "name=Ireland" --data-urlencode "name_ru=Ирландия"
curl ${API} -d code=IL --data-urlencode "name=Israel" --data-urlencode "name_ru=Израиль"
curl ${API} -d code=IT --data-urlencode "name=Italy" --data-urlencode "name_ru=Италия"
curl ${API} -d code=JM --data-urlencode "name=Jamaica" --data-urlencode "name_ru=Ямайка"
curl ${API} -d code=JP --data-urlencode "name=Japan" --data-urlencode "name_ru=Япония"
curl ${API} -d code=JE --data-urlencode "name=Jersey" --data-urlencode "name_ru=Джерси"
curl ${API} -d code=JO --data-urlencode "name=Jordan" --data-urlencode "name_ru=Иордания"
curl ${API} -d code=KZ --data-urlencode "name=Kazakhstan" --data-urlencode "name_ru=Казахстан"
curl ${API} -d code=KE --data-urlencode "name=Kenya" --data-urlencode "name_ru=Кения"
curl ${API} -d code=KI --data-urlencode "name=Kiribati" --data-urlencode "name_ru=Кирибати"
curl ${API} -d code=KP --data-urlencode "name=Korea Dem. People's Rep." --data-urlencode "name_ru=Корея, Народно-Демократическая Республика."
curl ${API} -d code=KR --data-urlencode "name=Korea, (South) Republic of" --data-urlencode "name_ru=Корея, (Южная) Республика"
curl ${API} -d code=KV --data-urlencode "name=Kosovo" --data-urlencode "name_ru=Косово"
curl ${API} -d code=KW --data-urlencode "name=Kuwait" --data-urlencode "name_ru=Кувейт"
curl ${API} -d code=KG --data-urlencode "name=Kyrgyzstan" --data-urlencode "name_ru=Кыргызстан"
curl ${API} -d code=LA --data-urlencode "name=Lao People's Democ. Rep." --data-urlencode "name_ru=Лаосская Народно-демократическая республика"
curl ${API} -d code=LV --data-urlencode "name=Latvia" --data-urlencode "name_ru=Латвия"
curl ${API} -d code=LB --data-urlencode "name=Lebanon" --data-urlencode "name_ru=Ливан"
curl ${API} -d code=LS --data-urlencode "name=Lesotho" --data-urlencode "name_ru=Лесото"
curl ${API} -d code=LR --data-urlencode "name=Liberia" --data-urlencode "name_ru=Либерия"
curl ${API} -d code=LY --data-urlencode "name=Libyan Arab Jamahiriya" --data-urlencode "name_ru=Ливийская Арабская Джамахирия"
curl ${API} -d code=LI --data-urlencode "name=Liechtenstein" --data-urlencode "name_ru=Лихтенштейн"
curl ${API} -d code=LT --data-urlencode "name=Lithuania" --data-urlencode "name_ru=Литва"
curl ${API} -d code=LU --data-urlencode "name=Luxembourg" --data-urlencode "name_ru=Люксембург"
curl ${API} -d code=MO --data-urlencode "name=Macao, (China)" --data-urlencode "name_ru=Макао, (Китай)"
curl ${API} -d code=MK --data-urlencode "name=Macedonia, TFYR" --data-urlencode "name_ru=Македония , Бывшая югославская"
curl ${API} -d code=MG --data-urlencode "name=Madagascar" --data-urlencode "name_ru=Мадагаскар"
curl ${API} -d code=MW --data-urlencode "name=Malawi" --data-urlencode "name_ru=Малави"
curl ${API} -d code=MY --data-urlencode "name=Malaysia" --data-urlencode "name_ru=Малайзия"
curl ${API} -d code=MV --data-urlencode "name=Maldives" --data-urlencode "name_ru=Мальдивские о-ва"
curl ${API} -d code=ML --data-urlencode "name=Mali" --data-urlencode "name_ru=Мали"
curl ${API} -d code=MT --data-urlencode "name=Malta" --data-urlencode "name_ru=Мальта"
curl ${API} -d code=IM --data-urlencode "name=Man, Isle of" --data-urlencode "name_ru=Остров Мэн"
curl ${API} -d code=MH --data-urlencode "name=Marshall Islands" --data-urlencode "name_ru=Маршалловы острова"
curl ${API} -d code=MQ --data-urlencode "name=Martinique (FR)" --data-urlencode "name_ru=Мартиника (FR)"
curl ${API} -d code=MR --data-urlencode "name=Mauritania" --data-urlencode "name_ru=Мавритания"
curl ${API} -d code=MU --data-urlencode "name=Mauritius" --data-urlencode "name_ru=Маврикий"
curl ${API} -d code=YT --data-urlencode "name=Mayotte (FR)" --data-urlencode "name_ru=Майотта (FR)"
curl ${API} -d code=MX --data-urlencode "name=Mexico" --data-urlencode "name_ru=Мексика"
curl ${API} -d code=FM --data-urlencode "name=Micronesia, Fed. States of" --data-urlencode "name_ru=Микронезия"
curl ${API} -d code=MD --data-urlencode "name=Moldova, Republic of" --data-urlencode "name_ru=Молдова"
curl ${API} -d code=MC --data-urlencode "name=Monaco" --data-urlencode "name_ru=Монако"
curl ${API} -d code=MN --data-urlencode "name=Mongolia" --data-urlencode "name_ru=Монголия"
curl ${API} -d code=CS --data-urlencode "name=Montenegro" --data-urlencode "name_ru=Черногория"
curl ${API} -d code=MS --data-urlencode "name=Montserrat" --data-urlencode "name_ru=Монтсеррат"
curl ${API} -d code=MA --data-urlencode "name=Morocco" --data-urlencode "name_ru=Марокко"
curl ${API} -d code=MZ --data-urlencode "name=Mozambique" --data-urlencode "name_ru=Мозамбик"
curl ${API} -d code=MM --data-urlencode "name=Myanmar (ex-Burma)" --data-urlencode "name_ru=Мьянма (бывшая Бирма)"
curl ${API} -d code=NA --data-urlencode "name=Namibia" --data-urlencode "name_ru=Намибия"
curl ${API} -d code=NR --data-urlencode "name=Nauru" --data-urlencode "name_ru=Науру"
curl ${API} -d code=NP --data-urlencode "name=Nepal" --data-urlencode "name_ru=Непал"
curl ${API} -d code=NL --data-urlencode "name=Netherlands" --data-urlencode "name_ru=Нидерланды"
curl ${API} -d code=AN --data-urlencode "name=Netherlands Antilles" --data-urlencode "name_ru=Нидерландские Антильские острова"
curl ${API} -d code=NC --data-urlencode "name=New Caledonia" --data-urlencode "name_ru=Новая Каледония"
curl ${API} -d code=NZ --data-urlencode "name=New Zealand" --data-urlencode "name_ru=Новая Зеландия"
curl ${API} -d code=NI --data-urlencode "name=Nicaragua" --data-urlencode "name_ru=Никарагуа"
curl ${API} -d code=NE --data-urlencode "name=Niger" --data-urlencode "name_ru=Нигер"
curl ${API} -d code=NG --data-urlencode "name=Nigeria" --data-urlencode "name_ru=Нигерия"
curl ${API} -d code=NU --data-urlencode "name=Niue" --data-urlencode "name_ru=Ниуэ"
curl ${API} -d code=NF --data-urlencode "name=Norfolk Island" --data-urlencode "name_ru=Остров Норфолк"
curl ${API} -d code=MP --data-urlencode "name=Northern Mariana Islands" --data-urlencode "name_ru=Северные Марианские острова"
curl ${API} -d code=NO --data-urlencode "name=Norway" --data-urlencode "name_ru=Норвегия"
curl ${API} -d code=OM --data-urlencode "name=Oman" --data-urlencode "name_ru=Оман"
curl ${API} -d code=PK --data-urlencode "name=Pakistan" --data-urlencode "name_ru=Пакистан"
curl ${API} -d code=PW --data-urlencode "name=Palau" --data-urlencode "name_ru=Palau"
curl ${API} -d code=PS --data-urlencode "name=Palestinian Territory" --data-urlencode "name_ru=Палестинская территория"
curl ${API} -d code=PA --data-urlencode "name=Panama" --data-urlencode "name_ru=Панама"
curl ${API} -d code=PG --data-urlencode "name=Papua New Guinea" --data-urlencode "name_ru=Папуа-Новая Гвинея"
curl ${API} -d code=PY --data-urlencode "name=Paraguay" --data-urlencode "name_ru=Парагвай"
curl ${API} -d code=PE --data-urlencode "name=Peru" --data-urlencode "name_ru=Перу"
curl ${API} -d code=PH --data-urlencode "name=Philippines" --data-urlencode "name_ru=Филиппины"
curl ${API} -d code=PN --data-urlencode "name=Pitcairn Island" --data-urlencode "name_ru=Остров Питкэрн"
curl ${API} -d code=PL --data-urlencode "name=Poland" --data-urlencode "name_ru=Польша"
curl ${API} -d code=PT --data-urlencode "name=Portugal" --data-urlencode "name_ru=Португалия"
curl ${API} -d code=PR --data-urlencode "name=Puerto Rico" --data-urlencode "name_ru=Пуэрто-Рико"
curl ${API} -d code=QA --data-urlencode "name=Qatar" --data-urlencode "name_ru=Катар"
curl ${API} -d code=RE --data-urlencode "name=Reunion (FR)" --data-urlencode "name_ru=Реюньон (FR)"
curl ${API} -d code=RU --data-urlencode "name=Russia (Russian Fed.)" --data-urlencode "name_ru=Россия (Российская Федерация)"
curl ${API} -d code=RW --data-urlencode "name=Rwanda" --data-urlencode "name_ru=Руанда"
curl ${API} -d code=BL --data-urlencode "name=Saint Barthelemy (FR)" --data-urlencode "name_ru=Санкт -Бартелеми (FR)"
curl ${API} -d code=SH --data-urlencode "name=Saint Helena (UK)" --data-urlencode "name_ru=Остров Святой Елены (Великобритания)"
curl ${API} -d code=KN --data-urlencode "name=Saint Kitts and Nevis" --data-urlencode "name_ru=Сент-Китс и Невис"
curl ${API} -d code=MF --data-urlencode "name=Saint Martin (FR)" --data-urlencode "name_ru=Сен-Мартен (FR)"
curl ${API} -d code=PM --data-urlencode "name=S Pierre & Miquelon(FR)" --data-urlencode "name_ru=S Пьер и Микелон (FR)"
curl ${API} -d code=VC --data-urlencode "name=S Vincent & Grenadines" --data-urlencode "name_ru=S -Винсент и Гренадины"
curl ${API} -d code=SM --data-urlencode "name=San Marino" --data-urlencode "name_ru=Сан - Марино"
curl ${API} -d code=ST --data-urlencode "name=Sao Tome and Principe" --data-urlencode "name_ru=Сан-Томе и Принсипи"
curl ${API} -d code=SA --data-urlencode "name=Saudi Arabia" --data-urlencode "name_ru=Саудовская Аравия"
curl ${API} -d code=SN --data-urlencode "name=Senegal" --data-urlencode "name_ru=Сенегал"
curl ${API} -d code=RS --data-urlencode "name=Serbia" --data-urlencode "name_ru=Сербия"
curl ${API} -d code=SC --data-urlencode "name=Seychelles" --data-urlencode "name_ru=Сейшельские острова"
curl ${API} -d code=SG --data-urlencode "name=Singapore" --data-urlencode "name_ru=Сингапур"
curl ${API} -d code=SK --data-urlencode "name=Slovakia" --data-urlencode "name_ru=Словакия"
curl ${API} -d code=SI --data-urlencode "name=Slovenia" --data-urlencode "name_ru=Словения"
curl ${API} -d code=SB --data-urlencode "name=Solomon Islands" --data-urlencode "name_ru=Соломоновы Острова"
curl ${API} -d code=SO --data-urlencode "name=Somalia" --data-urlencode "name_ru=Сомали"
curl ${API} -d code=ZA --data-urlencode "name=South Africa" --data-urlencode "name_ru=Южная Африка"
curl ${API} -d code=GS --data-urlencode "name=S.George & S.Sandwich" --data-urlencode "name_ru=S.George & S.Sandwich"
curl ${API} -d code=SS --data-urlencode "name=South Sudan" --data-urlencode "name_ru=Южный Судан"
curl ${API} -d code=ES --data-urlencode "name=Spain" --data-urlencode "name_ru=Испания"
curl ${API} -d code=LK --data-urlencode "name=Sri Lanka (ex-Ceilan)" --data-urlencode "name_ru=Шри-Ланка (бывший Цейлон)"
curl ${API} -d code=SD --data-urlencode "name=Sudan" --data-urlencode "name_ru=Судан"
curl ${API} -d code=SR --data-urlencode "name=Suriname" --data-urlencode "name_ru=Суринам"
curl ${API} -d code=SJ --data-urlencode "name=Svalbard & Jan Mayen Is." --data-urlencode "name_ru=Шпицберген и Ян-Майен."
curl ${API} -d code=SZ --data-urlencode "name=Swaziland" --data-urlencode "name_ru=Свазиленд"
curl ${API} -d code=SE --data-urlencode "name=Sweden" --data-urlencode "name_ru=Швеция"
curl ${API} -d code=CH --data-urlencode "name=Switzerland" --data-urlencode "name_ru=Швейцария"
curl ${API} -d code=SY --data-urlencode "name=Syrian Arab Republic" --data-urlencode "name_ru=Сирийская Арабская Республика"
curl ${API} -d code=TW --data-urlencode "name=Taiwan" --data-urlencode "name_ru=Тайвань"
curl ${API} -d code=TJ --data-urlencode "name=Tajikistan" --data-urlencode "name_ru=Таджикистан"
curl ${API} -d code=TZ --data-urlencode "name=Tanzania, United Rep. of" --data-urlencode "name_ru=Танзания , Объединенная Респ."
curl ${API} -d code=TH --data-urlencode "name=Thailand" --data-urlencode "name_ru=Таиланд"
curl ${API} -d code=TG --data-urlencode "name=Togo" --data-urlencode "name_ru=Того"
curl ${API} -d code=TK --data-urlencode "name=Tokelau" --data-urlencode "name_ru=Токелау"
curl ${API} -d code=TO --data-urlencode "name=Tonga" --data-urlencode "name_ru=Тонга"
curl ${API} -d code=TT --data-urlencode "name=Trinidad & Tobago" --data-urlencode "name_ru=Тринидад и Тобаго"
curl ${API} -d code=TN --data-urlencode "name=Tunisia" --data-urlencode "name_ru=Тунис"
curl ${API} -d code=TR --data-urlencode "name=Turkey" --data-urlencode "name_ru=Турция"
curl ${API} -d code=TM --data-urlencode "name=Turkmenistan" --data-urlencode "name_ru=Туркменистан"
curl ${API} -d code=TC --data-urlencode "name=Turks and Caicos Is." --data-urlencode "name_ru=Теркс и Кайкос ли."
curl ${API} -d code=TV --data-urlencode "name=Tuvalu" --data-urlencode "name_ru=Тувалу"
curl ${API} -d code=UG --data-urlencode "name=Uganda" --data-urlencode "name_ru=Уганда"
curl ${API} -d code=UA --data-urlencode "name=Ukraine" --data-urlencode "name_ru=Украина"
curl ${API} -d code=AE --data-urlencode "name=United Arab Emirates" --data-urlencode "name_ru=Объединенные Арабские Эмираты"
curl ${API} -d code=UK --data-urlencode "name=United Kingdom" --data-urlencode "name_ru=Великобритания"
curl ${API} -d code=US --data-urlencode "name=United States" --data-urlencode "name_ru=США"
curl ${API} -d code=UM --data-urlencode "name=US Minor Outlying Isl." --data-urlencode "name_ru=Экваториальные Острова (US)."
curl ${API} -d code=UY --data-urlencode "name=Uruguay" --data-urlencode "name_ru=Уругвай"
curl ${API} -d code=UZ --data-urlencode "name=Uzbekistan" --data-urlencode "name_ru=Узбекистан"
curl ${API} -d code=VU --data-urlencode "name=Vanuatu" --data-urlencode "name_ru=Вануату"
curl ${API} -d code=VA --data-urlencode "name=Vatican (Holy See)" --data-urlencode "name_ru=Ватикан"
curl ${API} -d code=VE --data-urlencode "name=Venezuela" --data-urlencode "name_ru=Венесуэла"
curl ${API} -d code=VN --data-urlencode "name=Viet Nam" --data-urlencode "name_ru=Вьетнам"
curl ${API} -d code=VI --data-urlencode "name=Virgin Islands, U.S." --data-urlencode "name_ru=Виргинские острова, США"
curl ${API} -d code=WF --data-urlencode "name=Wallis and Futuna" --data-urlencode "name_ru=Уоллис и Футуна"
curl ${API} -d code=EH --data-urlencode "name=Western Sahara" --data-urlencode "name_ru=Западная Сахара"
curl ${API} -d code=YE --data-urlencode "name=Yemen" --data-urlencode "name_ru=Йемен"
curl ${API} -d code=ZM --data-urlencode "name=Zambia" --data-urlencode "name_ru=Замбия"
curl ${API} -d code=ZW --data-urlencode "name=Zimbabwe" --data-urlencode "name_ru=Зимбабве"
